# Generated by Django 4.0.6 on 2022-07-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50, verbose_name='Назва проекта')),
                ('task_project', models.TextField(verbose_name='Про прект')),
            ],
        ),
    ]
