# Generated by Django 4.0.6 on 2022-07-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='working_hours',
            field=models.DateField(blank=True, help_text='введите время над проектом', null=True, verbose_name='время над проектом'),
        ),
    ]
